apiVersion: apps/v1
kind: Deployment
metadata:
  name: customeridentity-deployment
  namespace: rudii
  labels:
    app: customeridentityapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customeridentityapi
  template:
    metadata:
      namespace: rudii
      labels:
        app: customeridentityapi
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: customeridentityapi
          image: diptervacr.azurecr.io/customerserver:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq-service
            - name: IssueUri
              value: http://customeridentityapi-service.rudii.svc.cluster.local
            - name: ConnectionStrings__DefaultConnection
              value: "Server=mssql-deployment;Database=ParcelDelivery_CustomersDb;User Id=sa;Password=Password?123@;Encrypt=False;TrustServerCertificate=true"
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  namespace: rudii
  name: customeridentityapi-service
spec:
  type: LoadBalancer
  selector:
    app: customeridentityapi
  ports:
    - protocol: TCP
      port: 80
