apiVersion: apps/v1
kind: Deployment
metadata:
  name: packagetracking-deployment
  namespace: rudii
  labels:
    app: packagetrackingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packagetrackingapi
  template:
    metadata:
      namespace: rudii
      labels:
        app: packagetrackingapi
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: packagetrackingapi
          image: diptervacr.azurecr.io/packagetracking:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq-service
            - name: CacheSettings__ConnectionString
              value: redis-service
            - name: EmployeeIdentity__Authority
              value: http://40.114.180.13
            - name: CustomerIdentity__Authority
              value: http://10.224.0.5
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  namespace: rudii
  name: packagetrackingapi-service
spec:
  selector:
    app: packagetrackingapi
  ports:
    - protocol: TCP
      port: 80
