apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: rudii
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      namespace: rudii
      labels:
        app: angular
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: angular
          image: diptervacr.azurecr.io/webfrontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
---
apiVersion: v1
kind: Service
metadata:
  namespace: rudii
  name: angular-service
spec:
  type: LoadBalancer
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80
