apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-persistent-volume
  namespace: rudii
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rudii
  name: db-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rudii
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: PackageSendingDb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin1234
