version: '3.4'

services:
  packagedelivery.mongodb:
    container_name: packagedelivery_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  packagetracking.redisdb:
    container_name: packagetracking_redisdb
    restart: always
    ports:
      - "6379:6379"

  packagesending.postgresql:
    container_name: packagesending_postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=PackageSendingDb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  users.mssqldb:
    container_name: users_mssqldb
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password?123@"
      ACCEPT_EULA: "Y"

  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pda.hu
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
      - "5051:443"
    volumes:
      - pgadmin_data:/root/.pgadmin

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  packagedelivery.api:
    container_name: packagedelivery.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DatabaseSettings:ConnectionString=mongodb://packagedelivery_mongodb:27017
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
      - ConnectionStrings:HangfireConnection=Server=users_mssqldb;Database=ParcelDelivery_SchedulerDb;User Id=sa;Password=Password?123@;Encrypt=False;TrustServerCertificate=true
      - ConnectionStrings:HangfireConnectionCreateDb=Server=users_mssqldb;User Id=sa;Password=Password?123@;Encrypt=False;TrustServerCertificate=true
    depends_on:
      - packagedelivery.mongodb
      - rabbitmq
    ports:
      - "42010:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro
  
  packagetracking.api:
    container_name: packagetracking.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CacheSettings:ConnectionString=packagetracking_redisdb:6379
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - packagetracking.redisdb
      - rabbitmq
    ports:
      - "42011:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  packagesending.api:
    container_name: packagesending.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=packagesending_postgresql;Port=5432;Database=PackageSendingDb;User Id=admin;Password=admin1234;
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - packagesending.postgresql
      - rabbitmq
    ports:
      - "42012:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  employees.api:
    container_name: employees.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=users_mssqldb;Database=ParcelDelivery_EmployeesDb;User Id=sa;Password=Password?123@;Encrypt=False;TrustServerCertificate=true
    depends_on:
      - users.mssqldb
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  customers.api:
    container_name: customers.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Server=users_mssqldb;Database=ParcelDelivery_CustomersDb;User Id=sa;Password=Password?123@;Encrypt=False;TrustServerCertificate=true
    depends_on:
      - users.mssqldb
      - employees.api
    ports:
      - "5002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - packagesending.api
      - packagetracking.api
      - packagedelivery.api
      - employees.api
      - customers.api
    ports:
      - "42024:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro